version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LOG_LEVEL=${LOG_LEVEL}
      - BATCH_SIZE=${BATCH_SIZE}
      - GUNICORN_WORKERS=1
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5566
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
